version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "8808:8808"
    volumes:
    - bandfinder_data:/var/lib/mysql

volumes:
  bandfinder_data: